### ISSUE TITLE
yolo.h5 file is missing

### ISSUE THREAD

**Issue by gdmaru** [seansaito/ndsc_code_gakko_workshop#2]
I can see that file in Google Drive but not in Github here

**Comment by seansaito** [comment]
Yup, the `yolo.h5` weights file is about 250MB in size and GitHub has an upper limit of 100MB for file sizes. You need to download it from the Google Drive folder as specified in the README: https://github.com/seansaito/ndsc_code_gakko_workshop/blob/master/README.md
